# Generated by Django 3.2.9 on 2022-01-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.plant')),
                ('light', models.TextField(max_length=300)),
                ('water', models.TextField(max_length=300)),
                ('toxicity', models.CharField(choices=[('Severe', 'Severly toxic'), ('Mild', 'Mildy toxic'), ('None', 'No or low toxicity')], default='Severe', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Feeding Date')),
                ('type', models.CharField(max_length=200)),
                ('instructions', models.TextField(max_length=400)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
