# Generated by Django 3.2.9 on 2022-01-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220112_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Watering Date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feeding',
            name='type',
            field=models.CharField(default='Plant Food', max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='waterings',
            field=models.ManyToManyField(to='main_app.Watering'),
        ),
    ]
